version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/meinto/git-semver
    steps:
      - checkout
      - run: go get ./...
      - run: ./.circleci/build.sh
  deploy:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/meinto/git-semver
    steps:
      - checkout
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN v$(cat VERSION) build

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/